# Exam Code Toolkit

## Markov Stationary Distribution

In [11]:
import numpy as np

# Define the transfer matrix, P
P = np.array([[1/2, 1/4, 1/4],
              [1/2, 0, 1/2],
              [1/2, 1/4, 1/4]])

from numpy.linalg import eig

# Find the eigenvectors-eigenvalues
w, v = eig(np.transpose(P))

# Find the index of the eigenvalue equal to 1
for idx in range(len(w)):
    if abs(w[idx] - 1.0) < 1e-6: windex = idx

# Keep the eigenvector with unit eigenvalue
# and normalize it properly
result = v[:,windex]/v[:,windex].sum()

result

array([0.5, 0.2, 0.3])

## Gini Index

In [3]:
import numpy as np

Answer_1 = np.array([300,180]) # Format [+,-]
Answer_2 = np.array([80,440]) # Format [+,-]

Sum1 = Answer_1.sum()
Sum2 = Answer_2.sum()
TotSum = Sum1 + Sum2

Gini_1 = 1.0 - (Answer_1[0]/Sum1)**2 - (Answer_1[1]/Sum1)**2
Gini_2 = 1.0 - (Answer_2[0]/Sum2)**2 - (Answer_2[1]/Sum2)**2

Question = (Sum1*Gini_1 + Sum2*Gini_2)/TotSum

print(f'The Gini Index for Answer 1 = {Gini_1:.4f}.')
print(f'The Gini Index for Answer 2 = {Gini_2:.4f}.')

print(f'The Gini Index for the Question = {Question:.4f}.')

The Gini Index for Answer 1 = 0.4688.
The Gini Index for Answer 2 = 0.2604.
The Gini Index for the Question = 0.3604.


## Simulated Annealing

In [26]:
import numpy as np

# Define the studied function
def func(x):
    #return x**4 + x**3 - 5.0*(x**2)-x+10.0
    return 0.25*x**4 + (7.0/15.0)*x**3 - 0.8*x**2 - 0.8*x + 2.0 # <- sample exercise, for debugging

# Define the Temperature borders
Tstart, Tend = 2.0, 0.5
#Tstart, Tend = 2.0, 0.25 # <- sample exercise, for debugging

# Define the reduction percentage for the temperature
#perc = 0.2
perc = 0.3 # <- sample exercise, for debugging

# Define the starting x-point
#xc = 0.8
xc = 0.5 # <- sample exercise, for debugging

# Define the values used for proposed displacements
#group_1 = [0.21,-0.45,-0.73,0.12,-0.5,-0.66,-0.98,0.25,0.37]
group_1 = [-0.3040, 0.4923, -0.4430, -0.7023, -0.8728, -0.5724] # <- sample exercise, for debugging # -0.8868

# Define the values used to compare with resulting probability
#group_2 = [0.434, 0.052, 0.167, 0.923, 0.076]
group_2 = [0.0881, 0.7506, 0.0015] # <- sample exercise, for debugging

In [27]:
# Calculate the values of the temperature
Temps = []
T = Tstart
while T > Tend:
    Temps.append(T)
    T *= 1.0-perc
nsteps = len(Temps)

# Run the algorithm
Estart = func(xc)
gennumct = 0 # controls how many times we check group 2
for i in range(nsteps):
    print(f'Initiating step No. {i+1}.\n'+55*'*'+'\n')
    # Proposed step
    xprop = xc + group_1[i]
    Eprop = func(xprop)
    print(f'Proposed x = {xprop}, corresponding energy = {Eprop}')
    
    DE = Eprop-Estart
    # in this case the proposed energy is higher,
    # so Metropolis-Hastings has to check
    if DE > 0:
        print(f'DE is positive, i.e. the proposed energy is higher, so we perform the Metropolis-Hastings check.')
        Tc = Temps[i]
        pr = np.exp(-DE/Tc)
        gen_num = group_2[gennumct]
        gennumct += 1
        accepted = pr > gen_num
        if accepted:
            xc = xprop
            Estart = Eprop
            print(f'Calculated prob = {pr} > {gen_num}, so the step is accepted.')
            print(f'Current x = {xc}, current energy = {Estart}.\n')
        else:
            print(f'Calculated prob = {pr} < {gen_num}, so the step is NOT accepted.')
            print(f'Current x = {xc}, current energy = {Estart}.\n')
    else:
        # in this case, no need to check
        xc = xprop
        Estart = Eprop
        print(f'DE is negative, i.e. the proposed energy is lower, the step is automatically accepted.')
        print(f'Current x = {xc}, current energy = {Estart}.\n')

Initiating step No. 1.
*******************************************************

Proposed x = 0.196, corresponding energy = 1.8163499307306665
DE is positive, i.e. the proposed energy is higher, so we perform the Metropolis-Hastings check.
Calculated prob = 0.8426565662589519 > 0.0881, so the step is accepted.
Current x = 0.196, current energy = 1.8163499307306665.

Initiating step No. 2.
*******************************************************

Proposed x = 0.6883, corresponding energy = 1.2786397571528847
DE is negative, i.e. the proposed energy is lower, the step is automatically accepted.
Current x = 0.6883, current energy = 1.2786397571528847.

Initiating step No. 3.
*******************************************************

Proposed x = 0.24530000000000002, corresponding energy = 1.7634155978196753
DE is positive, i.e. the proposed energy is higher, so we perform the Metropolis-Hastings check.
Calculated prob = 0.6097725713602841 < 0.7506, so the step is NOT accepted.
Current x = 0.6

### Logistic Regression

1 step of logistic regression with SGD. 
For more steps, change X, Y to the appropriate values and use b_new as b . 

In [47]:
import numpy as np
from math import exp

# learning rate  
lr = 0.3                              
# Initialize [b0, b1, b2]
b = np.array([0.0, 0.0, 0.0])   
b_new=b

In [48]:
b = b_new
# Update X,Y values depending on the given dataset for each new step.
X = np.array([1.0, 2.7810836  , 2.550537003])   # [X0=1, X1, X2]
Y = 0

# Prediction 
p_pred = 1/(1 + exp(np.dot(b,X)) )

# Update step
b_new = b + lr * (Y - p_pred) * p_pred * (1-p_pred) * X

print('P_pred :', p_pred)
print('b_new :', b_new)

P_pred : 0.5
b_new : [-0.0375     -0.10429064 -0.09564514]


### Value Iteration

1. Create the grid.
2. Assign cells for starting position, Winning position and Losing position , as the values for them are freezed to 0 .
3. Assign probability of moving in the correct or perpendicular direction
4. Assign gamma and epochs parameters

In [137]:
import numpy as np

# Create the grid for the exercise given. Include the reward in each cell
grid = np.array([[ 0, 0, -5],[0, 0, +5]]) # [[(1,1), (1,2), (1,3)], [(2,1), (2,2), (2,3)]]

# Assign win and lose cells 
# If win cell is (2,3) stin ekfwnisi tote dineis (1,2) epeidi to array ksekinaei apo 0
Start = (0,0)
Win = (1,2)
Lose = (0,2)

# probability to move to the desired and not desired (slip) direction
p_desired = 0.8
p_slip = 0.1

# Discount factor gamma
gamma = 0.9
epochs=3


# Value initialization
V_i = np.zeros(grid.shape)
V_new = V_i

print('The Grid you created : \n', grid)
print('The initial values : \n',V_i)

The Grid you created : 
 [[ 0  0 -5]
 [ 0  0  5]]
The initial values : 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [138]:
for epoch in range(0, epochs) :
    print('\n \n ')
    print('********'*3, f' Epoch : {epoch + 1}', '********'*3)
    V_i = V_new
    for i in range(0, grid.shape[0]) :
        for j in range(0, grid.shape[1]) :
            # Taking care of bumping to walls 
            left = j if (j-1)<0 else j-1
            right = j if (j+1)>(grid.shape[1]-1) else j+1
            up = i if (i+1)>(grid.shape[0]-1) else i+1
            down = i if (i-1)<0 else i-1
            # print(f"i={i}  j={j}")
            # print(left,right,up,down)

            print(f'\n ****** Calculating grid cell V[{i+1,j+1}] *********')
            
            if (i,j)!=Win and (i,j)!=Lose and (i,j)!=Start :  # don't calculate for winning and losing cells, just assign 0 value
                
                a_left = p_desired*( grid[i][left] + gamma*V_i[i][left])  +  p_slip*(grid[up][j] + gamma*V_i[up][j]) + p_slip*(grid[down][j] + gamma*V_i[down][j])
                print(f'Action Left = {a_left}')
                a_right = p_desired*( grid[i][right] + gamma*V_i[i][right]) +  p_slip*(grid[up][j] + gamma*V_i[up][j]) + p_slip*(grid[down][j] + gamma*V_i[down][j])
                print(f'Action Right = {a_right}')
                a_up = p_desired*( grid[up][j] + gamma*V_i[up][j]) +  p_slip*(grid[i][left] + gamma*V_i[i][left]) + p_slip*(grid[i][right] + gamma*V_i[i][right])
                print(f'Action Up = {a_up}')
                a_down = p_desired*( grid[down][j] + gamma*V_i[down][j]) +  p_slip*(grid[i][left] + gamma*V_i[i][left]) + p_slip*(grid[i][right] + gamma*V_i[i][right])
                print(f'Action Down = {a_down}')

                actions = [a_left, a_right, a_up, a_down]
                action_names = [' Left ', ' Right ', ' Up ', ' Down ']
                max_a = max(actions)
                arg_max_a = np.argmax(actions)
                print(f'Maximum Value action is action={action_names[arg_max_a]}  with value={max_a}')

                V_new[i,j] = max_a
            else :
                print('This is Start/Win/Lose cell, assigning Value of zero [0]')
                V_new[i,j] = 0
                
    print(f'\n Values of matrix V after {epochs} epochs:')
    print(V_new)
    print('Flattened :', V_new.flatten())

print('\n')
print('============'*3)
print(f' Final values of matrix V after {epochs} epochs:')
print(V_new)
print('============'*3)


 
 
************************  Epoch : 1 ************************

 ****** Calculating grid cell V[(1, 1)] *********
This is Start/Win/Lose cell, assigning Value of zero [0]

 ****** Calculating grid cell V[(1, 2)] *********
Action Left = 0.0
Action Right = -4.0
Action Up = -0.5
Action Down = -0.5
Maximum Value action is action= Left   with value=0.0

 ****** Calculating grid cell V[(1, 3)] *********
This is Start/Win/Lose cell, assigning Value of zero [0]

 ****** Calculating grid cell V[(2, 1)] *********
Action Left = 0.0
Action Right = 0.0
Action Up = 0.0
Action Down = 0.0
Maximum Value action is action= Left   with value=0.0

 ****** Calculating grid cell V[(2, 2)] *********
Action Left = 0.0
Action Right = 4.0
Action Up = 0.5
Action Down = 0.5
Maximum Value action is action= Right   with value=4.0

 ****** Calculating grid cell V[(2, 3)] *********
This is Start/Win/Lose cell, assigning Value of zero [0]

 Values of matrix V after 3 epochs:
[[0. 0. 0.]
 [0. 4. 0.]]
Flattened : [0. 