In [26]:
import numpy as np
from numpy.linalg import eig

### PCA

In [27]:
data = np.array([[14.23,1.71,2.43],[13.2,1.78,2.14],[13.16,2.36,2.67]])

In [28]:
norm_data = np.array([[0.7,-0.33,-0.37],[-0.24,-0.17,0.41],[0.02,-0.27,0.26]])

In [29]:
cov_matrix = np.cov(norm_data.T)

In [30]:
cov_matrix

array([[ 0.2356    , -0.0362    , -0.2001    ],
       [-0.0362    ,  0.00653333,  0.0296    ],
       [-0.2001    ,  0.0296    ,  0.1713    ]])

In [31]:
values, vectors = eig(cov_matrix)
print("The eigenvalues of the normalized data are the following: ")
print(values)
print("The eigenvectors of the normalized data are the following: ")
print(vectors)

The eigenvalues of the normalized data are the following: 
[ 4.11513388e-01 -1.91173694e-17  1.91994564e-03]
The eigenvectors of the normalized data are the following: 
[[-0.75627955  0.55458317  0.34710048]
 [ 0.11468034  0.63468963 -0.76421037]
 [ 0.64411929  0.53815108  0.54360258]]


In [32]:
vectors_new = vectors[:2,:]

In [36]:
new_data = vectors_new.dot(norm_data.T)
new_data

array([[-0.84083531,  0.22953915, -0.07461692],
       [ 0.1535865 , -0.44874677, -0.36776729]])